FROM node:18.12-alpine

RUN apk add jq zsh libcurl python3 alpine-sdk curl-dev

RUN npm i npm@9.2.0 -g

RUN mkdir -p /tests
RUN mkdir -p /owl
RUN mkdir -p /example

RUN chown node:node /example

COPY --chown=node:node ./package.json ./package-lock.json /owl/

WORKDIR /owl
RUN npm install && npm cache clean --force

WORKDIR /tests

COPY --chown=node:node ./dist/ /owl/dist/
RUN npm install -g /owl

COPY --chown=node:node ./integration/local/tests /tests/

WORKDIR /example

CMD "owl" "--version"